-- =========================================================================
-- AI INTERVIEW PREPARATION SYSTEM - INITIAL SEED DATA
-- =========================================================================

-- 1. APTITUDE QUESTIONS SEED
INSERT INTO public.aptitude_questions (category, topic, difficulty, question, options, correct_option, explanation) VALUES
('Quantitative', 'Percentages', 'Intermediate', 'A shopkeeper marks an item at 25% above cost price and allows a discount of 10% for cash payment. What is his profit percentage?', '["10%", "12.5%", "15%", "17.5%"]'::jsonb, 1, 'Let CP = 100. Marked Price (MP) = 125. Selling Price with 10% discount = 125 * 0.9 = 112.5. Profit = 112.5 - 100 = 12.5%.'),
('Quantitative', 'Profit and Loss', 'Beginner', 'If the cost price of 12 pens is equal to the selling price of 8 pens, find the gain percentage.', '["25%", "33.33%", "50%", "66.67%"]'::jsonb, 2, 'Let CP of 1 pen = 1. CP of 8 pens = 8. SP of 8 pens = CP of 12 pens = 12. Profit = 12 - 8 = 4. Gain % = (4 / 8) * 100 = 50%.'),
('Quantitative', 'Time and Work', 'Intermediate', 'A can complete a piece of work in 12 days, and B can complete the same work in 18 days. If they work together for 4 days, what fraction of the work is left?', '["1/3", "4/9", "5/9", "2/3"]'::jsonb, 1, '1 day work of A+B = (1/12) + (1/18) = 5/36. 4 days work = 4 * (5/36) = 20/36 = 5/9. Work left = 1 - 5/9 = 4/9.'),
('Quantitative', 'Time, Speed and Distance', 'Advanced', 'A train 150 meters long takes 15 seconds to cross a bridge 300 meters long. What is the speed of the train in km/h?', '["72 km/h", "90 km/h", "108 km/h", "120 km/h"]'::jsonb, 2, 'Total distance = 150 + 300 = 450 meters. Speed in m/s = 450 / 15 = 30 m/s. Speed in km/h = 30 * (18 / 5) = 108 km/h.'),
('Quantitative', 'Probability', 'Intermediate', 'Two dice are rolled simultaneously. What is the probability that the sum of the numbers obtained is a prime number?', '["5/12", "7/18", "1/2", "5/18"]'::jsonb, 0, 'Possible sums that are prime: 2, 3, 5, 7, 11. Count of outcomes: 2: (1,1)[1], 3: (1,2),(2,1)[2], 5: (1,4),(2,3),(3,2),(4,1)[4], 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1)[6], 11: (5,6),(6,5)[2]. Total = 1 + 2 + 4 + 6 + 2 = 15. Probability = 15/36 = 5/12.'),
('Logical Reasoning', 'Number Systems', 'Frequently Asked', 'Find the next number in the series: 3, 7, 15, 31, 63, ?', '["126", "127", "128", "129"]'::jsonb, 1, 'The pattern is (2 * n) + 1 or +4, +8, +16, +32, +64. 63 * 2 + 1 = 127.'),
('Logical Reasoning', 'Logical Puzzles', 'Frequently Asked', 'Pointing to a photograph of a man, Rahul said, "His mother is the only daughter of my mother." How is Rahul related to the person in the photograph?', '["Father", "Uncle", "Brother", "Maternal Uncle"]'::jsonb, 3, ' Rahul''s mother''s only daughter is Rahul''s sister. The man''s mother is Rahul''s sister. Thus, Rahul is the maternal uncle of the man in the photo.');

-- 2. TECHNICAL QUESTIONS SEED
INSERT INTO public.technical_questions (role, topic, difficulty, question, expected_concepts, sample_answer) VALUES
('Software Developer', 'OOP', 'Intermediate', 'Explain the four pillars of Object-Oriented Programming (OOP) with real-world analogies.', '["Encapsulation", "Abstraction", "Inheritance", "Polymorphism"]'::jsonb, 'The four pillars are Encapsulation (bundling data and methods into a capsule like a medical pill or class), Abstraction (hiding implementation complexity and exposing clean interfaces like a car steering wheel), Inheritance (deriving child class properties from parent class like ElectricCar from Car), and Polymorphism (ability to take multiple forms such as method overloading and overriding).'),
('Software Developer', 'DBMS', 'Intermediate', 'What are ACID properties in Database Management Systems and why are they important?', '["Atomicity", "Consistency", "Isolation", "Durability"]'::jsonb, 'ACID stands for Atomicity (all-or-nothing transaction execution), Consistency (database transitions from one valid state to another maintaining all rules and constraints), Isolation (concurrent transactions execute independently without interference), and Durability (once committed, changes survive system crashes and are permanently recorded).'),
('Frontend Developer', 'Web Technologies', 'Intermediate', 'What is the difference between Virtual DOM and Real DOM, and how does React or modern UI reconciliation optimize performance?', '["Real DOM vs Virtual DOM", "Diffing Algorithm", "Reconciliation", "Batch Updates", "Repaint/Reflow reduction"]'::jsonb, 'The Real DOM is the browser tree structure where every update triggers reflow and repaint calculations. The Virtual DOM is an in-memory lightweight JavaScript representation. When state changes, a new virtual DOM tree is created, diffed against the previous tree using an efficient heuristic algorithm, and only the minimal required changes are batch-applied to the Real DOM, minimizing expensive layout recalculations.'),
('Backend Developer', 'APIs & Architecture', 'Advanced', 'What is the difference between REST and GraphQL? In what scenarios would you choose one over the other?', '["REST endpoints vs single endpoint", "Over-fetching & Under-fetching", "Payload flexibility", "Caching (HTTP vs client)", "Schema definition"]'::jsonb, 'REST uses standard HTTP methods across multiple resources with fixed endpoint contracts, benefiting from native HTTP caching. GraphQL uses a single endpoint with a strict typed schema allowing clients to query exactly the fields needed, eliminating over-fetching and under-fetching. REST is ideal for resource-oriented apps and standard microservices; GraphQL shines for complex mobile apps and aggregating data from multiple services.'),
('Full Stack Developer', 'System Design', 'Advanced', 'How does JWT (JSON Web Token) authentication work, and how do you mitigate security risks such as token theft and revocation?', '["Header.Payload.Signature", "Statelessness", "Access Token vs Refresh Token", "HttpOnly Cookies", "Revocation strategies / Blacklisting"]'::jsonb, 'A JWT contains three base64-encoded segments: Header, Payload, and cryptographic Signature. The server signs it using a secret or private key. The client includes it in headers. To mitigate risks: keep access token lifespans short (e.g. 15 mins), store tokens in HttpOnly Secure SameSite cookies to block XSS, use rotating Refresh Tokens in backend databases, and implement a revocation list or token versioning for forced logouts.');

-- 3. CODING / DSA QUESTIONS SEED
INSERT INTO public.coding_questions (title, role, topic, difficulty, description, examples, constraints, starter_code, test_cases) VALUES
('Two Sum', 'Software Developer', 'Arrays & Hash Maps', 'Beginner', 
'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.

You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.',
'[{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "Because nums[0] + nums[1] == 9, we return [0, 1]."}]'::jsonb,
ARRAY['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9', '-10^9 <= target <= 10^9', 'Only one valid answer exists.'],
'{"javascript": "function twoSum(nums, target) {\n    // Write your code here\n    const map = new Map();\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (map.has(complement)) {\n            return [map.get(complement), i];\n        }\n        map.set(nums[i], i);\n    }\n    return [];\n}", "python": "def two_sum(nums, target):\n    # Write your code here\n    lookup = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in lookup:\n            return [lookup[complement], i]\n        lookup[num] = i\n    return []"}'::jsonb,
'[{"input": "nums = [2,7,11,15], target = 9", "expected_output": "[0,1]", "is_hidden": false}, {"input": "nums = [3,2,4], target = 6", "expected_output": "[1,2]", "is_hidden": false}, {"input": "nums = [3,3], target = 6", "expected_output": "[0,1]", "is_hidden": true}]'::jsonb),

('Valid Parentheses', 'Software Developer', 'Stack', 'Beginner',
'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid.

An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
3. Every close bracket has a corresponding open bracket of the same type.',
'[{"input": "s = \"()[]{}\"", "output": "true", "explanation": "All brackets matched in correct order."}, {"input": "s = \"(]\"", "output": "false", "explanation": "Mismatched bracket types."}]'::jsonb,
ARRAY['1 <= s.length <= 10^4', 's consists of parentheses only "()[]{}"'],
'{"javascript": "function isValid(s) {\n    // Write your code here\n    const stack = [];\n    const pairs = { \")\": \"(\", \"}\": \"{\", \"]\": \"[\" };\n    for (const char of s) {\n        if (char in pairs) {\n            if (stack.pop() !== pairs[char]) return false;\n        } else {\n            stack.push(char);\n        }\n    }\n    return stack.length === 0;\n}", "python": "def is_valid(s):\n    # Write your code here\n    stack = []\n    pairs = {\")\": \"(\", \"}\": \"{\", \"]\": \"[\"}\n    for char in s:\n        if char in pairs:\n            if not stack or stack.pop() != pairs[char]:\n                return False\n        else:\n            stack.append(char)\n    return len(stack) == 0"}'::jsonb,
'[{"input": "s = \"()\"", "expected_output": "true", "is_hidden": false}, {"input": "s = \"()[]{}\"", "expected_output": "true", "is_hidden": false}, {"input": "s = \"(]\"", "expected_output": "false", "is_hidden": false}, {"input": "s = \"([{}])\"", "expected_output": "true", "is_hidden": true}]'::jsonb),

('Reverse Linked List', 'Software Developer', 'Linked Lists', 'Intermediate',
'Given the `head` of a singly linked list, reverse the list, and return the reversed list.',
'[{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]", "explanation": "The linked list pointers are reversed."}]'::jsonb,
ARRAY['The number of nodes in the list is the range [0, 5000].', '-5000 <= Node.val <= 5000'],
'{"javascript": "function reverseList(head) {\n    let prev = null;\n    let curr = head;\n    while (curr) {\n        let nextTemp = curr.next;\n        curr.next = prev;\n        prev = curr;\n        curr = nextTemp;\n    }\n    return prev;\n}", "python": "def reverse_list(head):\n    prev = None\n    curr = head\n    while curr:\n        next_temp = curr.next\n        curr.next = prev\n        prev = curr\n        curr = next_temp\n    return prev"}'::jsonb,
'[{"input": "head = [1,2,3,4,5]", "expected_output": "[5,4,3,2,1]", "is_hidden": false}, {"input": "head = [1,2]", "expected_output": "[2,1]", "is_hidden": false}]'::jsonb);

-- 4. HR QUESTIONS SEED
INSERT INTO public.hr_questions (category, question, key_evaluation_points) VALUES
('Introduction', 'Tell me about yourself and walk me through your journey in technology.', '["Structured narrative (Present -> Past -> Future)", "Key technical achievements", "Clarity and confidence", "Conciseness"]'::jsonb),
('Behavioral', 'Tell me about a time when you faced a difficult technical challenge or bug and how you resolved it.', '["STAR method (Situation, Task, Action, Result)", "Root cause analysis capability", "Persistence and learning outcomes"]'::jsonb),
('Situational', 'How do you handle disagreement with a teammate or technical lead regarding an architectural decision?', '["Empathy & professional communication", "Data-driven decision making", "Commitment to team alignment"]'::jsonb),
('Motivational', 'Why do you want to join this company and what makes you a great fit for this role?', '["Alignment with company vision", "Value proposition of candidate skills", "Long-term enthusiasm"]'::jsonb),
('Behavioral', 'What are your greatest strengths and an area you are actively working to improve?', '["Self-awareness", "Concrete examples of strengths", "Constructive, actionable growth mindset for weaknesses"]'::jsonb);
