-- =========================================================================
-- AI INTERVIEW PREPARATION SYSTEM - INITIAL SEED DATA
-- =========================================================================

-- 1. APTITUDE QUESTIONS SEED (35 Diverse Questions)
INSERT INTO public.aptitude_questions (category, topic, difficulty, question, options, correct_option, explanation) VALUES
('Quantitative', 'Percentages', 'Intermediate', 'A shopkeeper marks an item at 25% above cost price and allows a discount of 10% for cash payment. What is his profit percentage?', '["10%", "12.5%", "15%", "17.5%"]'::jsonb, 1, 'Let CP = 100. Marked Price (MP) = 125. Selling Price with 10% discount = 125 * 0.9 = 112.5. Profit = 112.5 - 100 = 12.5%.'),
('Quantitative', 'Profit and Loss', 'Beginner', 'If the cost price of 12 pens is equal to the selling price of 8 pens, find the gain percentage.', '["25%", "33.33%", "50%", "66.67%"]'::jsonb, 2, 'Let CP of 1 pen = 1. CP of 8 pens = 8. SP of 8 pens = CP of 12 pens = 12. Profit = 12 - 8 = 4. Gain % = (4 / 8) * 100 = 50%.'),
('Quantitative', 'Time and Work', 'Intermediate', 'A can complete a piece of work in 12 days, and B can complete the same work in 18 days. If they work together for 4 days, what fraction of the work is left?', '["1/3", "4/9", "5/9", "2/3"]'::jsonb, 1, '1 day work of A+B = (1/12) + (1/18) = 5/36. 4 days work = 4 * (5/36) = 20/36 = 5/9. Work left = 1 - 5/9 = 4/9.'),
('Logical Reasoning', 'Number Systems', 'Frequently Asked', 'Find the next number in the series: 3, 7, 15, 31, 63, ?', '["126", "127", "128", "129"]'::jsonb, 1, 'The pattern is (2 * n) + 1. 63 * 2 + 1 = 127.'),
('Logical Reasoning', 'Logical Puzzles', 'Frequently Asked', 'Pointing to a photograph of a man, Rahul said, "His mother is the only daughter of my mother." How is Rahul related to the person in the photograph?', '["Father", "Uncle", "Brother", "Maternal Uncle"]'::jsonb, 3, 'Rahul''s mother''s only daughter is Rahul''s sister. The man''s mother is Rahul''s sister. Thus, Rahul is the maternal uncle.'),
('Quantitative', 'Time, Speed and Distance', 'Advanced', 'A train 150 meters long takes 15 seconds to cross a bridge 300 meters long. What is the speed of the train in km/h?', '["72 km/h", "90 km/h", "108 km/h", "120 km/h"]'::jsonb, 2, 'Total distance = 150 + 300 = 450 meters. Speed in m/s = 450 / 15 = 30 m/s. Speed in km/h = 30 * (18 / 5) = 108 km/h.'),
('Quantitative', 'Probability', 'Intermediate', 'Two dice are rolled simultaneously. What is the probability that the sum of the numbers obtained is a prime number?', '["5/12", "7/18", "1/2", "5/18"]'::jsonb, 0, 'Prime sums possible: 2, 3, 5, 7, 11. Count of outcomes: 2 (1), 3 (2), 5 (4), 7 (6), 11 (2) = 15 out of 36. Probability = 15/36 = 5/12.'),
('Quantitative', 'Ratio and Proportion', 'Beginner', 'The ratio of the ages of A and B is 4:5. Six years hence, the ratio of their ages will become 5:6. What is the present age of A?', '["20 years", "24 years", "28 years", "30 years"]'::jsonb, 1, 'Let ages be 4x and 5x. (4x + 6) / (5x + 6) = 5/6 => 24x + 36 = 25x + 30 => x = 6. Present age of A = 4 * 6 = 24 years.'),
('Quantitative', 'Average', 'Beginner', 'The average score of a batsman in 10 innings was 44. How many runs must he score in the 11th inning to raise his average to 48?', '["84", "88", "92", "96"]'::jsonb, 1, 'Total runs in 10 innings = 10 * 44 = 440. Required total in 11 innings = 11 * 48 = 528. Required runs = 528 - 440 = 88.'),
('Quantitative', 'Simple and Compound Interest', 'Intermediate', 'A sum of money invested at Simple Interest doubles itself in 8 years. In how many years will it treble (become 3 times) at the same rate?', '["12 years", "14 years", "16 years", "20 years"]'::jsonb, 2, 'Doubling means SI = P in 8 years. Trebling means SI = 2P. Time taken for double the interest = 2 * 8 = 16 years.'),
('Quantitative', 'Simple and Compound Interest', 'Intermediate', 'Find the compound interest on $10,000 for 2 years at 10% per annum, compounded annually.', '["$2,000", "$2,100", "$2,200", "$2,050"]'::jsonb, 1, 'Amount = 10,000 * (1 + 0.10)^2 = 10,000 * 1.21 = $12,100. CI = 12,100 - 10,000 = $2,100.'),
('Quantitative', 'Permutation and Combination', 'Intermediate', 'In how many distinct ways can the letters of the word "LEADER" be arranged?', '["720", "360", "120", "180"]'::jsonb, 1, 'Word has 6 letters with "E" repeating 2 times. Total permutations = 6! / 2! = 720 / 2 = 360.'),
('Quantitative', 'Time and Work', 'Beginner', 'Pipe A can fill a tank in 20 minutes and Pipe B can fill it in 30 minutes. If both pipes are opened together, how long will it take to fill the tank?', '["10 minutes", "12 minutes", "15 minutes", "18 minutes"]'::jsonb, 1, 'Combined rate = 1/20 + 1/30 = 5/60 = 1/12. Time taken = 12 minutes.'),
('Quantitative', 'Time, Speed and Distance', 'Intermediate', 'Two cars start from two cities 300 km apart and travel towards each other at speeds of 60 km/h and 40 km/h respectively. After how many hours will they meet?', '["2.5 hours", "3 hours", "3.5 hours", "4 hours"]'::jsonb, 1, 'Relative speed = 60 + 40 = 100 km/h. Time to meet = 300 / 100 = 3 hours.'),
('Quantitative', 'Number Systems', 'Frequently Asked', 'What is the remainder when (7^19 + 2) is divided by 6?', '["1", "2", "3", "5"]'::jsonb, 2, '7 mod 6 = 1. Therefore 7^19 mod 6 = 1^19 mod 6 = 1. Adding 2 gives (1 + 2) mod 6 = 3 mod 6 = 3.'),
('Logical Reasoning', 'Logical Reasoning', 'Intermediate', 'Statements: All cats are dogs. All dogs are birds. Conclusions: I. All cats are birds. II. All birds are cats.', '["Only conclusion I follows", "Only conclusion II follows", "Both I and II follow", "Neither I nor II follows"]'::jsonb, 0, 'Cats ⊆ Dogs ⊆ Birds implies all cats are birds (I follows). But not all birds are necessarily cats (II does not follow).'),
('Logical Reasoning', 'Coding Patterns', 'Frequently Asked', 'If in a certain code language "PENCIL" is written as "QGODKN", how is "PAPER" written in that same code?', '["QBQFS", "QCQFS", "QBQES", "QBRFS"]'::jsonb, 0, 'Pattern is +1 for each letter: P(+1)->Q, A(+1)->B, P(+1)->Q, E(+1)->F, R(+1)->S. Hence PAPER becomes QBQFS.'),
('Logical Reasoning', 'Logical Reasoning', 'Beginner', 'A person walks 10 meters North, turns right and walks 15 meters, then turns right again and walks 10 meters. How far and in which direction is he from his starting point?', '["15 meters East", "15 meters West", "10 meters East", "25 meters North"]'::jsonb, 0, 'Moving 10m North and 10m South cancels the vertical displacement. The horizontal displacement is 15m to the East.'),
('Data Interpretation', 'Basic Data Interpretation', 'Beginner', 'A company produced 1200 units in 2021, 1500 units in 2022, and 1800 units in 2023. What is the percentage growth in production from 2021 to 2023?', '["33.33%", "40%", "50%", "60%"]'::jsonb, 2, 'Increase = 1800 - 1200 = 600 units. Percentage growth = (600 / 1200) * 100 = 50%.'),
('Quantitative', 'Ratio and Proportion', 'Intermediate', 'In what ratio must tea at $62 per kg be mixed with tea at $72 per kg so that the mixture is worth $65 per kg?', '["7:3", "3:7", "5:3", "3:5"]'::jsonb, 0, 'By rule of alligation: (72 - 65) : (65 - 62) = 7 : 3.'),
('Quantitative', 'Basic Quantitative Reasoning', 'Beginner', 'The sum of the present ages of a father and his son is 60 years. Six years ago, father''s age was five times the age of the son. What is the son''s present age?', '["12 years", "14 years", "16 years", "18 years"]'::jsonb, 1, '6 years ago sum was 60 - 12 = 48. Let son''s age 6 yrs ago be x; 5x + x = 48 => x = 8. Son''s present age = 8 + 6 = 14 years.'),
('Quantitative', 'Probability', 'Intermediate', 'A card is drawn at random from a standard well-shuffled pack of 52 cards. What is the probability of getting a King or a Heart?', '["4/13", "1/4", "17/52", "16/52"]'::jsonb, 0, 'Number of Kings = 4, Number of Hearts = 13, King of Hearts = 1. Favorable = 4 + 13 - 1 = 16. Probability = 16/52 = 4/13.'),
('Quantitative', 'Number Systems', 'Frequently Asked', 'What is the smallest 4-digit number that is completely divisible by 12, 15, and 18?', '["1020", "1080", "1100", "1180"]'::jsonb, 1, 'LCM(12, 15, 18) = 180. 1000 / 180 = 5 with remainder 100. Required number = 1000 + (180 - 100) = 1080.'),
('Quantitative', 'Permutation and Combination', 'Frequently Asked', 'In a room of 10 people, everyone shakes hands with everyone else exactly once. How many total handshakes take place?', '["45", "50", "90", "100"]'::jsonb, 0, 'Total handshakes = 10C2 = (10 * 9) / 2 = 45.'),
('Logical Reasoning', 'Number Systems', 'Intermediate', 'Find the missing number in the sequence: 2, 6, 12, 20, 30, 42, ?', '["52", "54", "56", "60"]'::jsonb, 2, 'The terms are n * (n + 1): 1*2=2, 2*3=6, 3*4=12, 4*5=20, 5*6=30, 6*7=42, 7*8 = 56.'),
('Quantitative', 'Time, Speed and Distance', 'Intermediate', 'A boat can travel with a speed of 13 km/h in still water. If the speed of the stream is 4 km/h, find the time taken by the boat to go 68 km downstream.', '["3 hours", "4 hours", "5 hours", "5.5 hours"]'::jsonb, 1, 'Downstream speed = 13 + 4 = 17 km/h. Time = 68 / 17 = 4 hours.'),
('Quantitative', 'Percentages', 'Intermediate', 'The population of a town increases by 10% annually. If its present population is 20,000, what will be the population after 2 years?', '["22,000", "24,000", "24,200", "24,400"]'::jsonb, 2, 'Population after 2 years = 20,000 * (1 + 0.10)^2 = 20,000 * 1.21 = 24,200.'),
('Quantitative', 'Profit and Loss', 'Frequently Asked', 'Find the single equivalent discount percentage for two successive discounts of 20% and 10%.', '["28%", "30%", "25%", "29%"]'::jsonb, 0, 'Equivalent discount = 20 + 10 - (20 * 10 / 100) = 30 - 2 = 28%.'),
('Logical Reasoning', 'Logical Reasoning', 'Intermediate', 'Five friends (P, Q, R, S, T) are sitting in a row facing North. S is between T and Q. Q is to the immediate left of R. P is to the immediate left of T. Who is sitting in the middle?', '["P", "T", "S", "Q"]'::jsonb, 2, 'Arrangement from left to right is P - T - S - Q - R. S is sitting in the exact middle.'),
('Logical Reasoning', 'Logical Reasoning', 'Frequently Asked', 'What is the angle between the hour hand and the minute hand of a clock at 3:30?', '["70 degrees", "75 degrees", "80 degrees", "85 degrees"]'::jsonb, 1, 'Angle = |30*H - (11/2)*M| = |30*3 - (11/2)*30| = |90 - 165| = 75 degrees.'),
('Logical Reasoning', 'Logical Reasoning', 'Frequently Asked', 'If January 1, 2006 was a Sunday, what day of the week was January 1, 2010?', '["Thursday", "Friday", "Saturday", "Sunday"]'::jsonb, 1, 'Odd days: 2006(1) + 2007(1) + 2008(2) + 2009(1) = 5 odd days. Sunday + 5 days = Friday.'),
('Quantitative', 'Time and Work', 'Advanced', 'A and B undertake to do a piece of work for $600. A alone can do it in 6 days while B alone can do it in 8 days. With the help of C, they finish it in 3 days. Find C''s share.', '["$75", "$100", "$125", "$150"]'::jsonb, 0, 'C''s 1-day work = 1/3 - (1/6 + 1/8) = 1/24. Work ratio A:B:C = 4:3:1. C''s share = (1/8) * 600 = $75.'),
('Quantitative', 'Basic Quantitative Reasoning', 'Beginner', 'Which of the following fractions is the largest: 3/4, 5/6, 7/9, 11/13?', '["3/4", "5/6", "7/9", "11/13"]'::jsonb, 3, 'Decimals: 3/4 = 0.75, 5/6 = 0.833, 7/9 = 0.777, 11/13 ≈ 0.846. Hence 11/13 is the largest.'),
('Logical Reasoning', 'Number Systems', 'Beginner', 'Find the odd one out from the given options: 27, 64, 125, 144, 216.', '["27", "64", "125", "144"]'::jsonb, 3, '27=3^3, 64=4^3, 125=5^3, 216=6^3 are all perfect cubes. 144 = 12^2 is a square, not a cube.'),
('Data Interpretation', 'Basic Data Interpretation', 'Beginner', 'A monthly family budget of $4,000 allocates 35% to rent, 25% to food, 15% to savings, and the rest to miscellaneous expenses. How much is spent on miscellaneous expenses?', '["$800", "$1,000", "$1,200", "$600"]'::jsonb, 1, 'Miscellaneous percentage = 100% - (35% + 25% + 15%) = 25%. Amount = 0.25 * 4,000 = $1,000.');

-- 2. TECHNICAL QUESTIONS SEED
INSERT INTO public.technical_questions (role, topic, difficulty, question, expected_concepts, sample_answer) VALUES
('Software Developer', 'OOP', 'Intermediate', 'Explain the four pillars of Object-Oriented Programming (OOP) with real-world analogies.', '["Encapsulation", "Abstraction", "Inheritance", "Polymorphism"]'::jsonb, 'The four pillars are Encapsulation (bundling data and methods into a capsule like a medical pill or class), Abstraction (hiding implementation complexity and exposing clean interfaces like a car steering wheel), Inheritance (deriving child class properties from parent class like ElectricCar from Car), and Polymorphism (ability to take multiple forms such as method overloading and overriding).'),
('Software Developer', 'DBMS', 'Intermediate', 'What are ACID properties in Database Management Systems and why are they important?', '["Atomicity", "Consistency", "Isolation", "Durability"]'::jsonb, 'ACID stands for Atomicity (all-or-nothing transaction execution), Consistency (database transitions from one valid state to another maintaining all rules and constraints), Isolation (concurrent transactions execute independently without interference), and Durability (once committed, changes survive system crashes and are permanently recorded).'),
('Frontend Developer', 'Web Technologies', 'Intermediate', 'What is the difference between Virtual DOM and Real DOM, and how does React or modern UI reconciliation optimize performance?', '["Real DOM vs Virtual DOM", "Diffing Algorithm", "Reconciliation", "Batch Updates", "Repaint/Reflow reduction"]'::jsonb, 'The Real DOM is the browser tree structure where every update triggers reflow and repaint calculations. The Virtual DOM is an in-memory lightweight JavaScript representation. When state changes, a new virtual DOM tree is created, diffed against the previous tree using an efficient heuristic algorithm, and only the minimal required changes are batch-applied to the Real DOM, minimizing expensive layout recalculations.'),
('Backend Developer', 'APIs & Architecture', 'Advanced', 'What is the difference between REST and GraphQL? In what scenarios would you choose one over the other?', '["REST endpoints vs single endpoint", "Over-fetching & Under-fetching", "Payload flexibility", "Caching (HTTP vs client)", "Schema definition"]'::jsonb, 'REST uses standard HTTP methods across multiple resources with fixed endpoint contracts, benefiting from native HTTP caching. GraphQL uses a single endpoint with a strict typed schema allowing clients to query exactly the fields needed, eliminating over-fetching and under-fetching. REST is ideal for resource-oriented apps and standard microservices; GraphQL shines for complex mobile apps and aggregating data from multiple services.'),
('Full Stack Developer', 'System Design', 'Advanced', 'How does JWT (JSON Web Token) authentication work, and how do you mitigate security risks such as token theft and revocation?', '["Header.Payload.Signature", "Statelessness", "Access Token vs Refresh Token", "HttpOnly Cookies", "Revocation strategies / Blacklisting"]'::jsonb, 'A JWT contains three base64-encoded segments: Header, Payload, and cryptographic Signature. The server signs it using a secret or private key. The client includes it in headers. To mitigate risks: keep access token lifespans short (e.g. 15 mins), store tokens in HttpOnly Secure SameSite cookies to block XSS, use rotating Refresh Tokens in backend databases, and implement a revocation list or token versioning for forced logouts.');

-- 3. CODING / DSA QUESTIONS SEED
INSERT INTO public.coding_questions (title, role, topic, difficulty, description, examples, constraints, starter_code, test_cases) VALUES
('Two Sum', 'Software Developer', 'Arrays & Hash Maps', 'Beginner', 
'Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.

You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.',
'[{"input": "nums = [2,7,11,15], target = 9", "output": "[0,1]", "explanation": "Because nums[0] + nums[1] == 9, we return [0, 1]."}]'::jsonb,
ARRAY['2 <= nums.length <= 10^4', '-10^9 <= nums[i] <= 10^9', '-10^9 <= target <= 10^9', 'Only one valid answer exists.'],
'{"javascript": "function twoSum(nums, target) {\n    // Write your code here\n    const map = new Map();\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (map.has(complement)) {\n            return [map.get(complement), i];\n        }\n        map.set(nums[i], i);\n    }\n    return [];\n}", "python": "def two_sum(nums, target):\n    # Write your code here\n    lookup = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in lookup:\n            return [lookup[complement], i]\n        lookup[num] = i\n    return []"}'::jsonb,
'[{"input": "nums = [2,7,11,15], target = 9", "expected_output": "[0,1]", "is_hidden": false}, {"input": "nums = [3,2,4], target = 6", "expected_output": "[1,2]", "is_hidden": false}, {"input": "nums = [3,3], target = 6", "expected_output": "[0,1]", "is_hidden": true}]'::jsonb),

('Valid Parentheses', 'Software Developer', 'Stack', 'Beginner',
'Given a string `s` containing just the characters `(`, `)`, `{`, `}`, `[` and `]`, determine if the input string is valid.

An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
3. Every close bracket has a corresponding open bracket of the same type.',
'[{"input": "s = \"()[]{}\"", "output": "true", "explanation": "All brackets matched in correct order."}, {"input": "s = \"(]\"", "output": "false", "explanation": "Mismatched bracket types."}]'::jsonb,
ARRAY['1 <= s.length <= 10^4', 's consists of parentheses only "()[]{}"'],
'{"javascript": "function isValid(s) {\n    // Write your code here\n    const stack = [];\n    const pairs = { \")\": \"(\", \"}\": \"{\", \"]\": \"[\" };\n    for (const char of s) {\n        if (char in pairs) {\n            if (stack.pop() !== pairs[char]) return false;\n        } else {\n            stack.push(char);\n        }\n    }\n    return stack.length === 0;\n}", "python": "def is_valid(s):\n    # Write your code here\n    stack = []\n    pairs = {\")\": \"(\", \"}\": \"{\", \"]\": \"[\"}\n    for char in s:\n        if char in pairs:\n            if not stack or stack.pop() != pairs[char]:\n                return False\n        else:\n            stack.append(char)\n    return len(stack) == 0"}'::jsonb,
'[{"input": "s = \"()\"", "expected_output": "true", "is_hidden": false}, {"input": "s = \"()[]{}\"", "expected_output": "true", "is_hidden": false}, {"input": "s = \"(]\"", "expected_output": "false", "is_hidden": false}, {"input": "s = \"([{}])\"", "expected_output": "true", "is_hidden": true}]'::jsonb),

('Reverse Linked List', 'Software Developer', 'Linked Lists', 'Intermediate',
'Given the `head` of a singly linked list, reverse the list, and return the reversed list.',
'[{"input": "head = [1,2,3,4,5]", "output": "[5,4,3,2,1]", "explanation": "The linked list pointers are reversed."}]'::jsonb,
ARRAY['The number of nodes in the list is the range [0, 5000].', '-5000 <= Node.val <= 5000'],
'{"javascript": "function reverseList(head) {\n    let prev = null;\n    let curr = head;\n    while (curr) {\n        let nextTemp = curr.next;\n        curr.next = prev;\n        prev = curr;\n        curr = nextTemp;\n    }\n    return prev;\n}", "python": "def reverse_list(head):\n    prev = None\n    curr = head\n    while curr:\n        next_temp = curr.next\n        curr.next = prev\n        prev = curr\n        curr = next_temp\n    return prev"}'::jsonb,
'[{"input": "head = [1,2,3,4,5]", "expected_output": "[5,4,3,2,1]", "is_hidden": false}, {"input": "head = [1,2]", "expected_output": "[2,1]", "is_hidden": false}]'::jsonb);

-- 4. HR QUESTIONS SEED
INSERT INTO public.hr_questions (category, question, key_evaluation_points) VALUES
('Introduction', 'Tell me about yourself and walk me through your journey in technology.', '["Structured narrative (Present -> Past -> Future)", "Key technical achievements", "Clarity and confidence", "Conciseness"]'::jsonb),
('Behavioral', 'Tell me about a time when you faced a difficult technical challenge or bug and how you resolved it.', '["STAR method (Situation, Task, Action, Result)", "Root cause analysis capability", "Persistence and learning outcomes"]'::jsonb),
('Situational', 'How do you handle disagreement with a teammate or technical lead regarding an architectural decision?', '["Empathy & professional communication", "Data-driven decision making", "Commitment to team alignment"]'::jsonb),
('Motivational', 'Why do you want to join this company and what makes you a great fit for this role?', '["Alignment with company vision", "Value proposition of candidate skills", "Long-term enthusiasm"]'::jsonb),
('Behavioral', 'What are your greatest strengths and an area you are actively working to improve?', '["Self-awareness", "Concrete examples of strengths", "Constructive, actionable growth mindset for weaknesses"]'::jsonb);
